# Generated by Django 4.2.2 on 2023-06-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('strength', models.PositiveBigIntegerField()),
                ('dexterity', models.PositiveBigIntegerField()),
                ('constitution', models.PositiveBigIntegerField()),
                ('intelligence', models.PositiveBigIntegerField()),
                ('wisdom', models.PositiveBigIntegerField()),
                ('charisma', models.PositiveBigIntegerField()),
            ],
        ),
    ]
