# Generated by Django 4.2.2 on 2023-06-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attack', models.PositiveBigIntegerField()),
                ('defense', models.PositiveBigIntegerField()),
                ('attack_per_round', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(to='characterapp.weapon'),
        ),
    ]
