# Generated by Django 4.2.2 on 2023-06-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterapp', '0002_weapon_character_weapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='characterapp.weapon'),
        ),
    ]
